---
# defaults file for docker_install
ansible_become: yes
ansible_user: "{{ vault_ansible_user }}"
ansible_ssh_private_key: "{{ vault_ansible_ssh_private_key }}"
ansible_become_password: "{{ vault_ansible_become_password }}"
