---
- name: Upgrade packages
  ansible.builtin.include_tasks: includes/upgrade_packages.yml
- name: Install requirements
  ansible.builtin.include_tasks: includes/install_requirements.yml
- name: Add Docker GPG key
  ansible.builtin.include_tasks: includes/add_gpg_key.yml
- name: Add Docker repository
  ansible.builtin.include_tasks: includes/add_repository.yml
- name: Add Docker engine
  ansible.builtin.include_tasks: includes/install_docker_engine.yml
- name: Add ansible user to Docker group
  ansible.builtin.include_tasks: includes/add_user_to_docker_group.yml
- name: Set Docker prune
  ansible.builtin.include_tasks: includes/set_docker_prune.yml
- name: Clean packages
  ansible.builtin.include_tasks: includes/clean_packages.yml
