---
- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
  when: 
    - ansible_distribution == "Debian"

- name: Install software-properties-common
  apt:
    name:
      - software-properties-common
  when: 
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version | int < 13
